module.exports = {
  apps: [
    {
      name: "boiler_plate",
      script: "./bin/www",
      watch: true,
      ignore_watch: ["node_modules", "public", "logs"],
      env_local: {
        PORT: 4800,
        NODE_ENV: "local",
        DOMAIN_URL: "http://127.0.0.1:4800",
        DB_MONGO_URL: "mongodb://localhost:27017/boiler_plate",
        JWT_SECRET: "jsonwebtoken",
        SMTP_PORT: 587,
        SMTP_HOST: "smtp.gmail.com",
        SMTP_SECURE_CONNECTION: "",
        SMTP_AUTH_USER: "smtp.devstree2020@gmail.com",
        SMTP_AUTH_PASSWORD: "hpwmqjrhmjtlofrs",
        SMTP_SOURCE_EMAIL: "smtp.devstree2020@gmail.com",
      },
      env: {
        PORT: 4800,
        NODE_ENV: "local",
        DOMAIN_URL: "http://127.0.0.1:4800",
        DB_MONGO_URL: "mongodb://localhost:27017/boiler_plate",
        JWT_SECRET: "jsonwebtoken",
        SMTP_PORT: 587,
        SMTP_HOST: "smtp.gmail.com",
        SMTP_SECURE_CONNECTION: "",
        SMTP_AUTH_USER: "smtp.devstree2020@gmail.com",
        SMTP_AUTH_PASSWORD: "hpwmqjrhmjtlofrs",
        SMTP_SOURCE_EMAIL: "smtp.devstree2020@gmail.com",
      },
      env_production: {
        PORT: 4800,
        NODE_ENV: "local",
        DOMAIN_URL: "http://127.0.0.1:4800",
        DB_MONGO_URL: "mongodb://localhost:27017/boiler_plate",
        JWT_SECRET: "jsonwebtoken",
        SMTP_PORT: 587,
        SMTP_HOST: "smtp.gmail.com",
        SMTP_SECURE_CONNECTION: "",
        SMTP_AUTH_USER: "smtp.devstree2020@gmail.com",
        SMTP_AUTH_PASSWORD: "hpwmqjrhmjtlofrs",
        SMTP_SOURCE_EMAIL: "smtp.devstree2020@gmail.com",
      },
      env_staging: {
        PORT: 4800,
        NODE_ENV: "local",
        DOMAIN_URL: "http://127.0.0.1:4800",
        DB_MONGO_URL: "mongodb://localhost:27017/boiler_plate",
        JWT_SECRET: "jsonwebtoken",
        SMTP_PORT: 587,
        SMTP_HOST: "smtp.gmail.com",
        SMTP_SECURE_CONNECTION: "",
        SMTP_AUTH_USER: "smtp.devstree2020@gmail.com",
        SMTP_AUTH_PASSWORD: "hpwmqjrhmjtlofrs",
        SMTP_SOURCE_EMAIL: "smtp.devstree2020@gmail.com",
      },
    },
  ],
};
